### ISSUE TITLE
conda install for PMP?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#323]
In 10 days the PMP EOS article will be published.   Shouldn't we have an experimental PMP conda build available before then, much like the recent UV-CDAT release at https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda   ?  @doutriaux1 @durack1

**Comment by doutriaux1** [comment]
Yep it's in the conda branch. @durack1 @gleckler1 quick questions:

 * name? `pcmdi_metrics` or `pmp` for conda package
* which organization? `uvcdat` like the rest of uvcdat or `PCMDI` like cmor?

**Comment by durack1** [comment]
pcmd_metrics vs pmp is up to Pete.. I'd vote the PCMDI group however..

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  

name => pcmdi_metrics 
organization =>  PCMDI

Here is confirmation the EOS article is going to be published this week or next.   Shall we copy over https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda to the PMP install instructions and modify as necessary?

**Comment by doutriaux1** [comment]
yes but the install part should be:

`conda install -c PCMDI pcmdi_metrics`

**Comment by durack1** [comment]
It seems that at least on crunchy, some perms issues are tripping us over:
```
[durack1@crunchy ~]$ /usr/local/uvcdat/Anaconda/bin/conda config --set ssl_verify False
[durack1@crunchy ~]$ /usr/local/uvcdat/Anaconda/bin/binstar config --set verify_ssl False
[durack1@crunchy ~]$ /usr/local/uvcdat/Anaconda/bin/conda install pcmdi_metrics -c pcmdi -c uvcdat
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ....................
Warning: 4 possible package resolutions (only showing differing packages):
	[u'jasper-1.900.1-UVCDAT.tar.bz2', u'ossuuid-1.6.2-UVCDAT.tar.bz2'],
	[u'jasper-1.900.1-UVCDAT.tar.bz2', u'ossuuid-1.6.2-PCMDI.tar.bz2'],
	[u'jasper-1.900.1-PCMDI.tar.bz2', u'ossuuid-1.6.2-PCMDI.tar.bz2'],
	[u'jasper-1.900.1-PCMDI.tar.bz2', u'ossuuid-1.6.2-UVCDAT.tar.bz2'],

Package plan for installation in environment /usr/local/uvcdat/Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pcmdi_metrics-1.0.5        |              PMP         1.0 MB

The following NEW packages will be INSTALLED:

    cdat_info:     2.4.1-UVCDAT                
    cdms2:         2.4.1-UVCDAT                
    cdtime:        2.4.1-UVCDAT                
    cdutil:        2.4.1-UVCDAT                
    clapack:       3.2.1-UVCDAT                
    distarray:     2.4.1-UVCDAT                
    dv3d:          2.4.1-UVCDAT                
    esmf:          ESMF_6_3_0rp1_ESMP_01-UVCDAT
    ffmpeg:        2.7.0-UVCDAT                
    g2clib:        1.4.0b-UVCDAT               
    genutil:       2.4.1-UVCDAT                
    jasper:        1.900.1-UVCDAT              
    lapack:        3.4.2-UVCDAT                
    libcdms:       2.4.1-UVCDAT                
    libcf:         1.0.beta11-UVCDAT           
    libnetcdf:     4.3.3.1-3                   
    openblas:      0.2.14-4                    
    ossuuid:       1.6.2-UVCDAT                
    pcmdi_metrics: 1.0.5-PMP                   
    proj4:         4.9.1-0                     
    regrid2:       2.4.1-UVCDAT                
    udunits2:      2.2.17-UVCDAT               
    unidata:       2.4.1-UVCDAT                
    vcs:           2.4.1-UVCDAT                
    vcsaddons:     2.4.1-UVCDAT                
    vtk:           uvcdat-uvcdat_master        
    x264:          20151006.2245-UVCDAT        
    yasm:          1.2.0-UVCDAT                

The following packages will be UPDATED:

    conda:         3.19.1-py27_0 --> 4.0.5-py27_0                
    libgfortran:   1.0-0         --> 3.0-0                       
    openssl:       1.0.2f-0      --> 1.0.2g-0                    
    pip:           8.0.2-py27_0  --> 8.1.1-py27_1                
    setuptools:    19.6.2-py27_0 --> 20.7.0-py27_0               
    wheel:         0.26.0-py27_1 --> 0.29.0-py27_0               
    xz:            5.0.5-0       --> 5.0.5-1                     

The following packages will be DOWNGRADED:

    numpy:         1.10.4-py27_0 --> 1.9.2-py27_2                

Proceed ([y]/n)? y

Fetching packages ...
pcmdi_metrics- 100% |#####################################################################################################################################| Time: 0:00:01   1.01 MB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the                                                                                                                  |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/usr/local/uvcdat/Anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/site-packages/conda/install.py", line 484, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/local/uvcdat/Anaconda/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 13] Permission denied: u'/usr/local/uvcdat/Anaconda/pkgs/clapack-3.2.1-UVCDAT.tar.bz2'
[durack1@crunchy ~]$ ls -al /usr/local/uvcdat/Anaconda/pkgs/clapack-3.2.1-UVCDAT.tar.bz2
-rw------- 1 root root 5324387 Apr 25 08:31 /usr/local/uvcdat/Anaconda/pkgs/clapack-3.2.1-UVCDAT.tar.bz2
```

**Comment by gleckler1** [comment]
@doutriaux1 pls fix this (PD's comment above) permission issue so that PMP can be tested (not done yet with conda install) on crunchy... then set up for oceanonly also... thanks.
