### ISSUE TITLE
Continuing build and test issues

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#372]
@doutriaux1 it seems that the [`travis` build tests are continuing to fail](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/142877787#L819-L837) - this time it appears that upstream issues with `cdms2` have caused problems:
```
$ python test/test_suite.py
Traceback (most recent call last):
  File "test/test_suite.py", line 2, in <module>
    import test_from_param
  File "/home/travis/build/PCMDI/pcmdi_metrics/test/test_from_param.py", line 9, in <module>
    import pcmdi_metrics
  File "/home/travis/miniconda/lib/python2.7/site-packages/pcmdi_metrics/__init__.py", line 2, in <module>
    import io  # noqa
  File "/home/travis/miniconda/lib/python2.7/site-packages/pcmdi_metrics/io/__init__.py", line 2, in <module>
    import base  # noqa
  File "/home/travis/miniconda/lib/python2.7/site-packages/pcmdi_metrics/io/base.py", line 2, in <module>
    import cdms2
  File "/home/travis/miniconda/lib/python2.7/site-packages/cdms2/__init__.py", line 30, in <module>
    from dataset import createDataset, openDataset, useNetcdf3, \
  File "/home/travis/miniconda/lib/python2.7/site-packages/cdms2/dataset.py", line 6, in <module>
    import Cdunif
ImportError: /home/travis/miniconda/lib/python2.7/site-packages/cdms2/Cdunif.so: undefined symbol: Getname
The command "python test/test_suite.py" exited with 1.
```

**Comment by durack1** [comment]
@doutriaux1 [`master` is now building successfully on linux](https://travis-ci.org/PCMDI/pcmdi_metrics/builds) should we amend the title of this issue to also get `OS X` working and then close this?

**Comment by durack1** [comment]
@doutriaux1 we've got `OS X` working too?

**Comment by doutriaux1** [comment]
not yet I'll open an issue for osx
