### ISSUE TITLE
Can't run the PMP demo on the default version from conda

### ISSUE THREAD

**Issue by jservonnat** [PCMDI/pcmdi_metrics#449]
@doutriaux1 @gleckler1 @durack1 I can't run the pmp_demo_1.py on a freshly installed PMP.
I do:
```
conda create -n PMP_master -c pcmdi -c uvcdat pcmdi_metrics
```
And then try to run:
```
pmp_demo_1.py
```
Is it working on your side?

**Comment by jservonnat** [comment]
Not working neither on my laptop nor on Ciclad (IPSL server).
I'm using Python 2.7.12 |Anaconda 4.2.0 on both sides.

**Comment by jservonnat** [comment]
Ok apparently it is coherent with #447.
We can close it in this case (after your confirmation)

**Comment by doutriaux1** [comment]
@jservonnat I updated the Linux side of uvcdat you probably need:
```
conda create -n PMP -c conda-forge -c uvcdat -c pcmdi pcmdi_metrics
```
Note that we now need conda-forge channel

**Comment by jservonnat** [comment]
@doutriaux1 it does work on Ciclad. Thank you!
But it still doesn't make it on my Mac laptop (using the same command line). Any suggestion?

**Comment by gleckler1** [comment]
I doubt the demo will work with the changes we have made to the json files.   We have not been putting any real effort yet into documentation of demos since our
emphasis is currently on advancing our framework and working directly with those who are already using the package.

**Comment by jservonnat** [comment]
@gleckler1 ok but actually the test is successful on Ciclad. Which is a good news regarding your comment ;).
I still have issues with the threads but we are on it with @doutriaux1.

**Comment by jservonnat** [comment]
@doutriaux1 @gleckler1 breaking good news: the PMP updated with the nightly channels does pass the test on my Mac.
But we still have the thread issue. We really need to fix it (I can't work on Ciclad because of that).

**Comment by durack1** [comment]
@jservonnat I was hitting a thread issue with a pre-2.8 version of UV-CDAT, the changes in https://github.com/UV-CDAT/uvcdat/commit/910814b19996f074adeb341575b9c4b0fabfcb3b fixed things for me.. You might want to check that your `cdat_info.py` that is being installed has the amendments in the change above

**Comment by doutriaux1** [comment]
@jservonnat I'm preparing the mac build as we speak should be ready in an hour or so.

**Comment by doutriaux1** [comment]
@jservonnat are you good now?

**Comment by jservonnat** [comment]
@doutriaux1 almost, there is (from what I've tested) only one error left:
```
pcmdi_metrics_driver.py -p /Users/jerome/anaconda2/envs/PMP/share/pmp/demo/pmp_input_parameters_demo1.py
[Press enter]
Traceback (most recent call last):
  File "/Users/jerome/anaconda2/envs/PMP/bin/pcmdi_metrics_driver.py", line 8, in <module>
    import pcmdi_metrics
  File "/Users/jerome/anaconda2/envs/PMP/lib/python2.7/site-packages/pcmdi_metrics/__init__.py", line 3, in <module>
    import pcmdi  # noqa
  File "/Users/jerome/anaconda2/envs/PMP/lib/python2.7/site-packages/pcmdi_metrics/pcmdi/__init__.py", line 5, in <module>
    import bias_xy  # noqa
ImportError: No module named bias_xy
```
The module bias_xy.py is actually named bias.py in pcmdi_metrics/pcmdi. I've renamed it and it works now. You can close it as soon as you've renamed pcmdi_metrics/pcmdi/bias.py by pcmdi_metrics/pcmdi/bias_xy.py .

**Comment by doutriaux1** [comment]
not sure what you got, in master i see:
https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/pcmdi/bias_xy.py

**Comment by jservonnat** [comment]
@doutriaux1 pretty weird indeed... I've also realized that I don't get the PMP parser, although it's on github (neither on my mac nor on Ciclad).
Do you guys have the same issue?

**Comment by doutriaux1** [comment]
looks like you trashed your git env, I would clone fresh

**Comment by jservonnat** [comment]
I'm only doing conda but is git coming into play?

**Comment by durack1** [comment]
@jservonnat I've had to rebuild my anaconda environment a few times now.. It seems that once you've created a number of separate environments and then updated these things get out of sync (anaconda sets up links between all these different versions across environments).

The way I have solved these issues, is to rename the anaconda dir, and then completely reinstall anaconda, and then build new environments using the latest uv-cdat/pmp versions.. That has solved all my issues to date

**Comment by doutriaux1** [comment]
@jservonnat if you accidentally install pmp into your "root" env of conda (it happened last week to @glekcler1 ) then you're hosed, try removing your CONDA_PREFIX/lib/python2.7/site-packages/pcmdi*

C.

**Comment by jservonnat** [comment]
@durack1: I've re-installed anaconda2 on both my Mac and Ciclad, then installed the PMP with:
```
conda create -n PMP_master -c conda-forge -c pcmdi -c uvcdat pcmdi_metrics
```
I've checked before and after updating the PMP with:
```
conda update pcmdi_metrics vcs vcsaddons -c pcmdi/label/nightly -c uvcdat/label/nightly
```
And still no pmp_parser.py in pcmdi_metrics/pcmdi (actually, nowhere else).

@doutriaux1: I've looked at my /home/jservon/anaconda2 (root) but no pcmdi* module in lib/python2.7/site-packages/

Of course I can technically get the source code of the master or a branch to get the pmp_parser, but it's a bit weird that it doesn't come with conda...
It's not happening to you guys?

**Comment by jservonnat** [comment]
And I don't have the JSONs class neither in pcmdi_metrics/pcmdi/io.py...
What am I doing wrong?

**Comment by durack1** [comment]
@jservonnat the JSON class is in [src/python/io/base.py](https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/io/base.py#L188-L200)

Can you confirm that you are installing the [linux-64/pcmdi_metrics-2016.10.20-0.tar.bz2](https://anaconda.org/PCMDI/pcmdi_metrics/files) file on linux, or equivalent OSX version? Anything before this will not likely include what you want to use

**Comment by durack1** [comment]
@jservonnat when I try with your command line above, I'm sourcing the `1.1.1` release:
```
[durack1ml:~] durack1% conda create -n pmp -c conda-forge -c pcmdi -c uvcdat pcmdi_metrics
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /Users/durack1/anaconda2/envs/pmp:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    proj4-4.9.3                |                1         497 KB  conda-forge
    mpfr-3.1.4                 |                2         483 KB  conda-forge
    freetype-2.7               |                0         791 KB  conda-forge
    gcc-4.8.5                  |                7        55.5 MB
    requests-2.12.1            |           py27_0         740 KB  conda-forge
    pcmdi_metrics-1.1.1        |              PMP          56 KB  pcmdi
    ------------------------------------------------------------
                                           Total:        58.0 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0                       conda-forge
    cdat_info:       2.8-py27_2                        uvcdat     
    cdms2:           2.8-np111py27_2                   uvcdat     
    cdtime:          2.8-np111py27_2                   uvcdat     
    cdutil:          2.8-py27_2                        uvcdat     
    certifi:         2016.9.26-py27_0                  conda-forge
    clapack:         3.2.1-2                           uvcdat     
    cloog:           0.18.0-0                                     
    curl:            7.49.1-1                          conda-forge
    distarray:       2.8-py27_2                        uvcdat     
    dv3d:            2.8-py27_2                        uvcdat     
    esmf:            ESMF_6_3_0rp1_ESMP_01-np111py27_0 uvcdat     
    expat:           2.1.0-2                           conda-forge
    ffmpeg:          2.8.6-2                           conda-forge
    freetype:        2.7-0                             conda-forge
    g2clib:          1.6.0-2                           conda-forge
    gcc:             4.8.5-7                                      
    genutil:         2.8-np111py27_2                   uvcdat     
    gmp:             6.1.1-1                           conda-forge
    hdf4:            4.2.12-0                          conda-forge
    hdf5:            1.8.17-7                          conda-forge
    isl:             0.12.2-1                                     
    jasper:          1.900.1-3                         conda-forge
    jpeg:            9b-0                              conda-forge
    lapack:          3.6.1-1                           conda-forge
    libcdms:         2.8-2                             uvcdat     
    libcf:           1.0.beta11-py27_2                 uvcdat     
    libdrs_c:        1.0.1-2                           uvcdat     
    libdrs_f:        1.0.1-2                           uvcdat     
    libgcc:          4.8.5-1                                      
    libgfortran:     3.0.0-0                           conda-forge
    libnetcdf:       4.4.1-0                           conda-forge
    libpng:          1.6.26-0                          conda-forge
    libtiff:         4.0.6-7                           conda-forge
    mkl:             11.3.3-0                                     
    mpc:             1.0.3-1                           conda-forge
    mpfr:            3.1.4-2                           conda-forge
    ncurses:         5.9-9                             conda-forge
    numpy:           1.11.2-py27_0                                
    openssl:         1.0.2h-2                          conda-forge
    ossuuid:         1.6.2-2                           uvcdat     

    pcmdi_metrics:   1.1.1-PMP                         pcmdi      

    pip:             9.0.1-py27_0                      conda-forge
    proj4:           4.9.3-1                           conda-forge
    python:          2.7.12-1                          conda-forge
    readline:        6.2-0                             conda-forge
    requests:        2.12.1-py27_0                     conda-forge
    setuptools:      28.8.0-py27_0                     conda-forge
    sqlite:          3.13.0-1                          conda-forge
    tk:              8.5.19-0                          conda-forge
    udunits2:        2.2.20-1                          conda-forge
    unidata:         2.8-np111py27_2                   uvcdat     
    vcs:             2.8-py27_2                        uvcdat     
    vcsaddons:       2.8-py27_2                        uvcdat     
    vtk-cdat:        7.1.0.2.8-py27_2                  uvcdat     
    wheel:           0.29.0-py27_0                     conda-forge
    x264:            20131217-1                        conda-forge
    xz:              5.2.2-0                           conda-forge
    zlib:            1.2.8-3                           conda-forge
```

**Comment by durack1** [comment]
@jservonnat this will get you there:
```
[durack1ml:~] durack1% conda create -n pmp -c conda-forge -c pcmdi/label/nightly -c uvcdat pcmdi_metrics
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /Users/durack1/anaconda2/envs/pmp:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cdp-1.0.1                  |                0          11 KB  uvcdat
    proj4-4.9.3                |                1         497 KB  conda-forge
    mpfr-3.1.4                 |                2         483 KB  conda-forge
    freetype-2.7               |                0         791 KB  conda-forge
    gcc-4.8.5                  |                7        55.5 MB
    requests-2.12.1            |           py27_0         740 KB  conda-forge
    pcmdi_metrics-2016.10.20   |                0         121 KB  pcmdi/label/nightly
    ------------------------------------------------------------
                                           Total:        58.1 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.9.26-0                       conda-forge        
    cdat_info:       2.8-py27_2                        uvcdat             
    cdms2:           2.8-np111py27_2                   uvcdat             
    cdp:             1.0.1-0                           uvcdat             
    cdtime:          2.8-np111py27_2                   uvcdat             
    cdutil:          2.8-py27_2                        uvcdat             
    certifi:         2016.9.26-py27_0                  conda-forge        
    clapack:         3.2.1-2                           uvcdat             
    cloog:           0.18.0-0                                             
    curl:            7.49.1-1                          conda-forge        
    distarray:       2.8-py27_2                        uvcdat             
    dv3d:            2.8-py27_2                        uvcdat             
    esmf:            ESMF_6_3_0rp1_ESMP_01-np111py27_0 uvcdat             
    expat:           2.1.0-2                           conda-forge        
    ffmpeg:          2.8.6-2                           conda-forge        
    freetype:        2.7-0                             conda-forge        
    g2clib:          1.6.0-2                           conda-forge        
    gcc:             4.8.5-7                                              
    genutil:         2.8-np111py27_2                   uvcdat             
    gmp:             6.1.1-1                           conda-forge        
    hdf4:            4.2.12-0                          conda-forge        
    hdf5:            1.8.17-7                          conda-forge        
    isl:             0.12.2-1                                             
    jasper:          1.900.1-3                         conda-forge        
    jpeg:            9b-0                              conda-forge        
    lapack:          3.6.1-1                           conda-forge        
    libcdms:         2.8-2                             uvcdat             
    libcf:           1.0.beta11-py27_2                 uvcdat             
    libdrs_c:        1.0.1-2                           uvcdat             
    libdrs_f:        1.0.1-2                           uvcdat             
    libgcc:          4.8.5-1                                              
    libgfortran:     3.0.0-0                           conda-forge        
    libnetcdf:       4.4.1-0                           conda-forge        
    libpng:          1.6.26-0                          conda-forge        
    libtiff:         4.0.6-7                           conda-forge        
    mkl:             11.3.3-0                                             
    mpc:             1.0.3-1                           conda-forge        
    mpfr:            3.1.4-2                           conda-forge        
    ncurses:         5.9-9                             conda-forge        
    numpy:           1.11.2-py27_0                                        
    openssl:         1.0.2h-2                          conda-forge        
    ossuuid:         1.6.2-2                           uvcdat            
 
    pcmdi_metrics:   2016.10.20-0                      pcmdi/label/nightly

    pip:             9.0.1-py27_0                      conda-forge        
    proj4:           4.9.3-1                           conda-forge        
    python:          2.7.12-1                          conda-forge        
    readline:        6.2-0                             conda-forge        
    requests:        2.12.1-py27_0                     conda-forge        
    setuptools:      28.8.0-py27_0                     conda-forge        
    sqlite:          3.13.0-1                          conda-forge        
    tk:              8.5.19-0                          conda-forge        
    udunits2:        2.2.20-1                          conda-forge        
    unidata:         2.8-np111py27_2                   uvcdat             
    vcs:             2.8-py27_2                        uvcdat             
    vcsaddons:       2.8-py27_2                        uvcdat             
    vtk-cdat:        7.1.0.2.8-py27_2                  uvcdat             
    wheel:           0.29.0-py27_0                     conda-forge        
    x264:            20131217-1                        conda-forge        
    xz:              5.2.2-0                           conda-forge        
    zlib:            1.2.8-3                           conda-forge 
```

**Comment by doutriaux1** [comment]
@durack1 I believe the issue here is that @jservonnat installed an older version of `pmp` in his `root` env which seems to superseed whatever env he creates now.

**Comment by durack1** [comment]
@doutriaux1 the examples below should sort him out.. This make me think we need to push a `1.2.0` or similar to the main channel soon

**Comment by jservonnat** [comment]
@doutriaux1 apparently not... I've checked in both of my root and there is no pcmdi* module:
```
MacBook-Pro-de-Servonnat:~ jerome$ ls /Users/jerome/anaconda2/lib/python2.7/site-packages/pcmdi*
ls: /Users/jerome/anaconda2/lib/python2.7/site-packages/pcmdi*: No such file or directory
```
@durack1 your command actually works for me ;). There is a subtile difference between what I was doing and what you do: I use to request "-c uvcdat/label/nightly" and you ask for "-c uvcdat". The 
difference between both is that with the uvcdat/label/nightly you get:
```
    pcmdi_metrics: 1.1.1-PMP pcmdi --> 2016.10.14-0 pcmdi/label/nightly
```
And with -c uvcdat you get:
```
The following NEW packages will be INSTALLED:

    cdp:           1.0.1-0   uvcdat

The following packages will be UPDATED:

    pcmdi_metrics: 1.1.1-PMP pcmdi  --> 2016.10.20-0 pcmdi/label/nightly
```
Good that it works now but does that make sense to you?

**Comment by jservonnat** [comment]
@doutriaux1 @durack1 @gleckler1 And by the way, should the conda default version be in line with the github master? In other words, do you expect the installation protocole described in the wiki to get you the same code as what can be seen on the github master? Because it is not what happens for me...

**Comment by zshaheen** [comment]
@jservonnat @doutriaux1 @durack1 @gleckler1 The code on the master branch is sometimes in a flux, thus is make sense for the default installation to be a stable version of pmp. If the user does want the latest code from the github master, all they need to go is look on the link below and get the latest code from there:  [https://anaconda.org/PCMDI/pcmdi_metrics/files](https://anaconda.org/PCMDI/pcmdi_metrics/files). We now have automatic nighties.

**Comment by jservonnat** [comment]
@zshaheen indeed ;), I've noticed that I was installing a version 2016.11.21-0 on my linux machine (it is still the 2016.10.20-0 on my mac but I guess there are good reasons for that). Congratulations and many thanks for the nightly!
Thank you also for the explanation, it is clear now.
@doutriaux1 @durack1 @gleckler1 @zshaheen It might be worth clarifying the documentation on the wiki page on the Anaconda installation (difference between github master and default conda pmp version, and how to get the latest nightly version). What do you think?

**Comment by durack1** [comment]
@jservonnat are we good to close this now?

**Comment by jservonnat** [comment]
@durack1 Yes we can!
