### ISSUE TITLE
Catch problems with parameter filenames including hyphen

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#511]
With v1.1.2 the following error occurred:
```
(PMP112) duro@ocean:[170906_PaperPlots_OceanMetrics]:[6312]> pcmdi_metrics_driver_legacy.py -p cmip5_picontrol_pmp-parameterfile_thetao.py
/export/duro/anaconda2/envs/PMP112/lib/python2.7/site-packages/unidata/__init__.py:2: UserWarning: unidata package is deprecated please use genutil.udunits instead of unidata.udunits
  warnings.warn("unidata package is deprecated please use genutil.udunits instead of unidata.udunits")
Traceback (most recent call last):
  File "/export/duro/anaconda2/envs/PMP112/bin/pcmdi_metrics_driver_legacy.py", line 131, in <module>
    exec("import %s as parameters" % fnm)
  File "<string>", line 1
    import cmip5_picontrol_pmp-parameterfile_thetao as parameters
                              ^
SyntaxError: invalid syntax
```

**Comment by gleckler1** [comment]
parameter files cannot include a '-'
