### ISSUE TITLE
include parameter files for monsoon_wang and diurnal_covey

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/pcmdi_metrics#535]

**Comment by gleckler1** [comment]
@doutriaux1   OK I've created a branch (535_pjg_monsoon_diurnal_parameterfiles) with a test parameter file (examples/parameter_files/test_inparams-mpindex_compute.py).  This points to data on oceanonly.... **better would be to automatically download file or use readily accessible test-case data**.   I will add an example for the diurnal next.

**Comment by gleckler1** [comment]
@doutriaux1   There is now also a test parameter file for the first diurnal code.   This works on data avail on crunchy.   Like the monsoon example mentioned above (same branch and subdir), the test param for diurnal would be good to be "self contained", ie., somehow able to run with the test data we have in the repository, or perhaps hanging off a website.

**Comment by gleckler1** [comment]
@doutriaux1  We should discuss whether or not these test_parameter files rely on the small test data on the repo or if we pull down larger data on the fly to provide a more informative test case

**Comment by doutriaux1** [comment]
@gleckler1 when we have tests relying on bigger dataset I'll add them to the suite, but skip them on travis

**Comment by gleckler1** [comment]
@doutriaux1  Right.   So your task with this branch ((535_pjg_monsoon_diurnal_parameterfiles) is to set up the parameter files I've added to work with the test suite.

**Comment by gleckler1** [comment]
@doutriaux1 currently the tests in this PR point to data in crunchy.   Can you fix them to point to the test data suite so that a user can run them?

**Comment by gleckler1** [comment]
@doutriaux1  diurnal param file no longer working.... changes to dask since you wrote this last September?

(pmp_0808_py2.7) bash-4.1$ compositeDiurnalStatisticsWrapped.py -p test_inparams_compositeDiurnalStatistics.py
done
MODPATH: /work/cmip5-test/new/amip/atmos/3hr/pr/
TEMPLATE: cmip5.IPSL-CM5A-LR.amip.r1i1p1.3hr.atmos.3hr.pr.000000.v*.xml
FILES: ['/work/cmip5-test/new/amip/atmos/3hr/pr/cmip5.IPSL-CM5A-LR.amip.r1i1p1.3hr.atmos.3hr.pr.000000.v20110427.xml']
PARAMS: [<pcmdi_metrics.diurnal.common.INPUT object at 0x7fd4cc4c9810>]
/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/context.py:23: UserWarning: The dask.set_options function has been deprecated. Please use dask.config.set instead
  warnings.warn("The dask.set_options function has been deprecated. "
/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/base.py:835: UserWarning: The get= keyword has been deprecated. Please use the scheduler= keyword instead with the name of the desired scheduler like 'threads' or 'processes'
  warnings.warn("The get= keyword has been deprecated. "
Traceback (most recent call last):
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/bin/compositeDiurnalStatisticsWrapped.py", line 226, in <module>
    cdp.cdp_run.multiprocess(compute, params, num_workers=args.num_workers)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/cdp/cdp_run.py", line 21, in multiprocess
    results = bag.map(func).compute(num_workers=num_workers)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/base.py", line 402, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/local.py", line 505, in get_async
    raise_exception(exc, tb)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/local.py", line 274, in execute_task
    result = _execute_task(task, data)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/local.py", line 255, in _execute_task
    return func(*args2)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/bag/core.py", line 1554, in reify
    seq = list(seq)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/dask/bag/core.py", line 1714, in map_chunk
    yield f(*a)
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/bin/compositeDiurnalStatisticsWrapped.py", line 39, in compute
    reverted = template.reverse(os.path.basename(fileName))
  File "/export_backup/gleckler1/anaconda2/envs/pmp_0808_py2.7/lib/python2.7/site-packages/genutil/Filler.py", line 170, in reverse
    raise "Invalid pattern sent"
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by doutriaux1** [comment]
is it new env?

**Comment by gleckler1** [comment]
@doutriaux1 just created with conda create -n pmp_0808_py2.7 -c cdat/label/nightly -c conda-forge -c cdat -c pcmdi/label/nightly -c pcmdi cdat pcmdi_metrics python=2.7

**Comment by gleckler1** [comment]
@doutriaux1  Need to get this one working again before release.   Seems like the dask stuff is still a moving target.   the --bash option you setup for clim-cmor is a functioning temporary solution.  I'm not sure if the better thing to do with diurnal (via param file) is to fix it or to overhall it to use parallelize_driver.py

**Comment by doutriaux1** [comment]
on it should be done tomorrow (finger crossed)
