### ISSUE TITLE
Mac vs Linux

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/pcmdi_metrics#538]
I updated all baselines on Linux, now ran it on Mac, 5 tests are failing. Here is the summary:

`test_pmp_basic_test_parameters_file`

```
Comparing: /git/pcmdi_metrics/pcmdi_install_test_results/metrics_results/installationTest/tos_2.5x2.5_esmf_linear_metrics.json /git/pcmdi_metrics/tests/pcmdi/installationTest/tos_2.5x2.5_esmf_linear_metrics.json atol: 0.0 rtol: 0.005
Error for: GFDL-ESM2G,  default,  r1i1p1,  TROPICS,  rms_y,  ann,  ( 0, 1, 0, 2, 8, 0, ). Test value 0.709 vs expected value: 0.713 realtive: 0.561%
Error for: GFDL-ESM2G,  default,  r1i1p1,  global,  bias_xy,  djf,  ( 0, 1, 0, 3, 0, 1, ). Test value 0.077 vs expected value: 0.078 realtive: 1.282%
```

`testSavg_fourierWrappedInOut`
```
Traceback (most recent call last):
  File "/git/pcmdi_metrics/tests/test_pmp_diurnal.py", line 77, in testSavg_fourierWrappedInOut
    self.runJsoner("savg_fourierWrappedInOut.py","pr_Jul_1999-2005_savg_DiurnalFourier.json")
  File "/git/pcmdi_metrics/tests/test_pmp_diurnal.py", line 61, in runJsoner
    self.assertEqual(test["RESULTS"],good["RESULTS"])
AssertionError: {u'CMCC': {u'TROPICS': {u'harmonic2': {u'pha_avg_lnd': 4.630479623191498, u'amp_ [truncated]... != {u'CMCC': {u'TROPICS': {u'harmonic2': {u'pha_avg_lnd': 4.630479623191498, u'amp_ [truncated]...
Diff is 2824 characters long. Set self.maxDiff to None to see it.
```

`test_pmp_keep_going_on_error_varname`

```
Comparing: /git/pcmdi_metrics/pcmdi_install_test_results/metrics_results/keep_going_on_error_varnameTest/tos_2.5x2.5_esmf_linear_metrics.json /git/pcmdi_metrics/tests/pcmdi/keep_going_on_error_varnameTest/tos_2.5x2.5_esmf_linear_metrics.json atol: 0.0 rtol: 0.005
Error for: GFDL-ESM2G,  default,  r1i1p1,  TROPICS,  rms_y,  ann,  ( 0, 1, 0, 2, 8, 0, ). Test value 0.709 vs expected value: 0.713 realtive: 0.561%
Error for: GFDL-ESM2G,  default,  r1i1p1,  global,  bias_xy,  djf,  ( 0, 1, 0, 3, 0, 1, ). Test value 0.077 vs expected value: 0.078 realtive: 1.282%
E
```

`test_pmp_region_specs`

```
Comparing: /git/pcmdi_metrics/pcmdi_install_test_results/metrics_results/customRegions/tos_2.5x2.5_esmf_linear_metrics.json /git/pcmdi_metrics/tests/pcmdi/customRegions/tos_2.5x2.5_esmf_linear_metrics.json atol: 0.0 rtol: 0.005
Error for: GFDL-ESM2G,  default,  r1i1p1,  TROPICS,  rms_y,  ann,  ( 0, 1, 0, 2, 8, 0, ). Test value 0.709 vs expected value: 0.713 realtive: 0.561%
Error for: GFDL-ESM2G,  default,  r1i1p1,  global,  bias_xy,  djf,  ( 0, 1, 0, 3, 0, 1, ). Test value 0.077 vs expected value: 0.078 realtive: 1.282%
E
```

`test_pmp_salinity_test`

```
('comparing:', '/git/pcmdi_metrics/pcmdi_install_test_results/metrics_results/salinityTest/sos_2.5x2.5_esmf_linear_metrics.json', '/git/pcmdi_metrics/tests/pcmdi/salinityTest/sos_2.5x2.5_esmf_linear_metrics.json')
Comparing: /git/pcmdi_metrics/pcmdi_install_test_results/metrics_results/salinityTest/sos_2.5x2.5_esmf_linear_metrics.json /git/pcmdi_metrics/tests/pcmdi/salinityTest/sos_2.5x2.5_esmf_linear_metrics.json atol: 0.0 rtol: 0.005
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  bias_xy,  jja,  ( 0, 0, 0, 0, 0, 2, ). Test value -0.149 vs expected value: -0.146 realtive: 2.055%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  bias_xy,  mam,  ( 0, 0, 0, 0, 0, 3, ). Test value 0.087 vs expected value: 0.092 realtive: 5.435%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  bias_xy,  son,  ( 0, 0, 0, 0, 0, 4, ). Test value 0.048 vs expected value: 0.050 realtive: 4.000%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  cor_xy,  djf,  ( 0, 0, 0, 0, 1, 1, ). Test value 0.850 vs expected value: 0.860 realtive: 1.163%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  mae_xy,  djf,  ( 0, 0, 0, 0, 2, 1, ). Test value 0.572 vs expected value: 0.566 realtive: 1.060%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  mae_xy,  mam,  ( 0, 0, 0, 0, 2, 3, ). Test value 0.411 vs expected value: 0.406 realtive: 1.232%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  rms_xy,  djf,  ( 0, 0, 0, 0, 6, 1, ). Test value 0.882 vs expected value: 0.869 realtive: 1.496%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  rms_xy,  mam,  ( 0, 0, 0, 0, 6, 3, ). Test value 0.587 vs expected value: 0.569 realtive: 3.163%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  rmsc_xy,  djf,  ( 0, 0, 0, 0, 9, 1, ). Test value 0.829 vs expected value: 0.815 realtive: 1.718%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  NHEX,  rmsc_xy,  mam,  ( 0, 0, 0, 0, 9, 3, ). Test value 0.580 vs expected value: 0.561 realtive: 3.387%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  bias_xy,  ann,  ( 0, 0, 0, 1, 0, 0, ). Test value 0.122 vs expected value: 0.125 realtive: 2.400%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  bias_xy,  jja,  ( 0, 0, 0, 1, 0, 2, ). Test value -0.013 vs expected value: -0.012 realtive: 8.333%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  cor_xy,  ann,  ( 0, 0, 0, 1, 1, 0, ). Test value 0.678 vs expected value: 0.671 realtive: 1.043%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  mae_xy,  ann,  ( 0, 0, 0, 1, 2, 0, ). Test value 0.555 vs expected value: 0.559 realtive: 0.716%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  rms_devzm,  ann,  ( 0, 0, 0, 1, 5, 0, ). Test value 0.547 vs expected value: 0.561 realtive: 2.496%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  rms_xy,  ann,  ( 0, 0, 0, 1, 6, 0, ). Test value 0.887 vs expected value: 0.900 realtive: 1.444%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  rmsc_xy,  ann,  ( 0, 0, 0, 1, 9, 0, ). Test value 0.878 vs expected value: 0.891 realtive: 1.459%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  std-obs_xy,  ann,  ( 0, 0, 0, 1, 10, 0, ). Test value 1.130 vs expected value: 1.140 realtive: 0.877%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  SHEX,  std-obs_xy_devzm,  ann,  ( 0, 0, 0, 1, 11, 0, ). Test value 0.564 vs expected value: 0.577 realtive: 2.253%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  bias_xy,  ann,  ( 0, 0, 0, 2, 0, 0, ). Test value -0.162 vs expected value: -0.163 realtive: 0.613%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  bias_xy,  djf,  ( 0, 0, 0, 2, 0, 1, ). Test value -0.178 vs expected value: -0.180 realtive: 1.111%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  bias_xy,  jja,  ( 0, 0, 0, 2, 0, 2, ). Test value -0.173 vs expected value: -0.175 realtive: 1.143%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  bias_xy,  mam,  ( 0, 0, 0, 2, 0, 3, ). Test value -0.105 vs expected value: -0.107 realtive: 1.869%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  bias_xy,  son,  ( 0, 0, 0, 2, 0, 4, ). Test value -0.190 vs expected value: -0.191 realtive: 0.524%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  cor_xy,  djf,  ( 0, 0, 0, 2, 1, 1, ). Test value 0.850 vs expected value: 0.860 realtive: 1.163%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  rmsc_xy,  djf,  ( 0, 0, 0, 2, 9, 1, ). Test value 0.508 vs expected value: 0.505 realtive: 0.594%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std-obs_xy,  jja,  ( 0, 0, 0, 2, 10, 2, ). Test value 0.954 vs expected value: 0.948 realtive: 0.633%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std-obs_xy,  son,  ( 0, 0, 0, 2, 10, 4, ). Test value 0.998 vs expected value: 0.991 realtive: 0.706%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy,  ann,  ( 0, 0, 0, 2, 13, 0, ). Test value 0.949 vs expected value: 0.955 realtive: 0.628%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy,  djf,  ( 0, 0, 0, 2, 13, 1, ). Test value 0.967 vs expected value: 0.973 realtive: 0.617%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy,  jja,  ( 0, 0, 0, 2, 13, 2, ). Test value 0.950 vs expected value: 0.956 realtive: 0.628%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy,  mam,  ( 0, 0, 0, 2, 13, 3, ). Test value 0.981 vs expected value: 0.987 realtive: 0.608%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy,  son,  ( 0, 0, 0, 2, 13, 4, ). Test value 0.997 vs expected value: 1.003 realtive: 0.598%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xy_devzm,  ann,  ( 0, 0, 0, 2, 14, 0, ). Test value 0.854 vs expected value: 0.860 realtive: 0.698%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  TROPICS,  std_xyt,  ann,  ( 0, 0, 0, 2, 15, 0, ). Test value 0.984 vs expected value: 0.990 realtive: 0.606%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  global,  bias_xy,  ann,  ( 0, 0, 0, 3, 0, 0, ). Test value 0.021 vs expected value: 0.022 realtive: 4.545%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  global,  bias_xy,  djf,  ( 0, 0, 0, 3, 0, 1, ). Test value -0.086 vs expected value: -0.087 realtive: 1.149%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  global,  bias_xy,  jja,  ( 0, 0, 0, 3, 0, 2, ). Test value -0.123 vs expected value: -0.124 realtive: 0.806%
Error for: GFDL-CM3,  JPL-Aquarius-v2,  r1i1p1,  global,  cor_xy,  mam,  ( 0, 0, 0, 3, 1, 3, ). Test value 0.820 vs expected value: 0.830 realtive: 1.205%
E
```

I will investigate the diurnal error. What are you guys thinking of the other erros @taylor13 @gleckler1 @durack1

**Comment by gleckler1** [comment]
@doutriaux1 @taylor13 @durack1   CD, I believe **ALL** of the tests above involve masking.  It would be helpful to know how MAC and LINUX compare for cases without masking.   Additionally, I believe all tests above (except diurnal not yet working) are from ocean native grids.   Good to know, but it would also be useful to know how MAC/LINUX compare with regular grids (with and without masking). 

BYW... what is the Decision needed now?
