### ISSUE TITLE
Problems picking up existing cdat install

### ISSUE THREAD

**Issue by durack1** [PCMDI/pcmdi_metrics#73]
I've just come across this problem, where my path doesn't include a valid cdat install (I scrubbed it), however the installer is finding one:
```
-- Installing: /export/durack1/140916_pcmdi_metrics/PCMDI_METRICS/Externals/share/cmake-2.8/completions/ctest                
returning from build subshell with code: [1]                                                                                 

installed CMake version = 2.8.12

Checking for *UV* CDAT (Python+CDMS) master install_metrics.bash: line 139: /export/durack1/140916_pcmdi_metrics/PCMDI_METRICS/bin/python: No such file or directory                                                                                      
No python in your install directory, trying your PATH                                                                        
esgf-v1.7.0-770-g63d988a                                                                                                     
you have a valid cdat in your path                                                                                           
It is located at: /usr                                                                                                       
install_metrics.bash: line 148: /export/durack1/140916_pcmdi_metrics/PCMDI_METRICS/bin/setup_runtime.sh: No such file or directory                                                                                                                        
After setup_cdat /usr                                                                                                        
Traceback (most recent call last):                                                                                           
  File "setup.py", line 3, in <module>                                                                                       
    import numpy                                                                                                             
  File "/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>                   
    from . import add_newdocs                                                                                                
  File "/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>                 
    from numpy.lib import add_newdoc                                                                                         
  File "/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>                 
    from .type_check import *                                                                                                
  File "/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>              
    import numpy.core.numeric as _nx                                                                                         
  File "/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
AttributeError: PyCapsule_Import "datetime.datetime_CAPI" is not valid
```
My path looks like:
```
[durack1@oceanonly ~/140916_pcmdi_metrics]$ env | grep PATH
PATH=/export/durack1/bin/downloads/ferret6.9/140611_build/bin:./:/export/durack1/git/pylib:/export/durack1/git/cmip5:/export/durack1/git/cmip3:/export/durack1/.local/bin:/export/durack1/bin/downloads/ghostscript9.14/140611_binaries:/export/durack1/bin/downloads/p7zip9.20.1/130123_build/p7zip_9.20.1/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
PYTHONPATH=/usr/local/uvcdat/2014-08-22/lib/python2.7/site-packages:/usr/local/uvcdat/2014-08-22/Externals/lib/paraview-4.1/site-packages:/export/durack1/.local/lib/python2.7/site-packages:/export/durack1/git/pylib:/export/durack1/git/cmip5:/export/durack1/git/cmip3:/usr/local/uvcdat/2014-08-13/bin
MATLABPATH=/work/durack1/csiro/eez_data/software/matlab:/work/durack1/csiro/netcdf_matlab:/work/durack1/csiro/toolbox-local/csirolib:/work/durack1/csiro/toolbox-local/m_map:/work/durack1/matlab:/work/durack1/matlab/cm_and_cb_utilities:/work/durack1/matlab/dunn/mld/progs:/work/durack1/matlab/export_fig:/work/durack1/matlab/freezeColors:/work/durack1/matlab/gamma_n:/work/durack1/matlab/gsw_matlab_v3_04:/work/durack1/matlab/gsw_matlab_v3_04/html:/work/durack1/matlab/gsw_matlab_v3_04/library:/work/durack1/matlab/gsw_matlab_v3_04/pdf:/work/durack1/matlab/gsw_matlab_v3_04/thermodynamics_from_t:/work/durack1/matlab/inpaint_nans:/work/durack1/matlab/real2rgb:/work/durack1/matlab/seawater_ver3_3:/work/durack1/matlab/jsonlab_1.0beta
LD_LIBRARY_PATH=/usr/local/uvcdat/2014-08-22/lib:/usr/local/uvcdat/2014-08-22/Externals/lib:/usr/local/uvcdat/2014-08-22/Externals/lib/paraview-4.1:
UVCDAT_SETUP_PATH=/usr/local/uvcdat/2014-08-22
```

**Comment by durack1** [comment]
@doutriaux1 this needs you to generate the `*.csh`...
