### ISSUE TITLE
mean climate "no reference dataset" error

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#879]
@acordonez reported this issue:

Error message:
```
INFO::2022-10-18 13:54::pcmdi_metrics::E3SM:: REGION: global
Traceback (most recent call last):
  File "/home/ordonez4/miniconda3/envs/_CMEC_pcmdi_metrics/bin/mean_climate_driver.py", line 7, in <module>
    driver.run_diags()
  File "/home/ordonez4/miniconda3/envs/_CMEC_pcmdi_metrics/lib/python3.10/site-packages/pcmdi_metrics/pcmdi/mean_climate_metrics_driver.py", line 64, in run_diags
    self.run_reference_and_test_comparison()
  File "/home/ordonez4/miniconda3/envs/_CMEC_pcmdi_metrics/lib/python3.10/site-packages/pcmdi_metrics/pcmdi/mean_climate_metrics_driver.py", line 173, in run_reference_and_test_comparison
    raise RuntimeError("No reference dataset found!")
RuntimeError: No reference dataset found!
```
 
Contents of parameter file:
```python
import datetime
import glob
import os

case_id = 'E3SM'
test_data_set = ['E3SM-1-0']
vars = ['hfls', 'hfss', 'hur', 'hus', 'pr', 'prw', 'psl', 'rlds', 'rldscs', 'rlutcs', 'rsdscs', 'rsdt', 'rsus', 'sfcWind', 'ta_850', 'tas', 'tauu', 'tauv', 'ts', 'ua_850', 'va_850', 'zg_850']
filename_template = 'AC/%(variable)_mon_E3SM-1-0_historical_r1i1p1f1_gr_195001_201412.195001-201412.AC.v20221018.nc'
sftlf_filename_template = 'fx/sftlf_fx_E3SM-1-0_historical_r1i1p1f1_gr.nc'
generate_sftlf = False
reference_data_set = ['all']
target_grid = '2.5x2.5'
regrid_tool = 'regrid2'
regrid_method = 'linear'
regrid_tool_ocn = 'esmf'
regrid_method_ocn = 'linear'
save_test_clims = False
filename_output_template = '%(model_version)_%(variable)_%(region).nc'
compute_climatologies = False
test_data_path = '/home/ordonez4/cmec_run_inputs'
reference_data_path = '/p/user_pub/PCMDIobs/obs4MIPs_clims'
metrics_output_path = '/home/ordonez4/cmec_run_outputs/PMP/mean_climate'
test_clims_interpolated_output = '/home/ordonez4/cmec_run_outputs/PMP/mean_climate/test_clims'
cmec = True
```

PMP version: v2.5.0

**Comment by lee1043** [comment]
@gleckler1 the obs catalogue json file needs update
