### ISSUE TITLE
Error in precipitation variability demo 

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#900]
In the [Demo](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_7_precip_variability.ipynb)'s cell [5], I am getting the following error. 

```
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230218/bin/variability_across_timescales_PS_driver.py", line 4, in <module>
    __import__('pkg_resources').run_script('pcmdi-metrics==2.5.1', 'variability_across_timescales_PS_driver.py')
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/pcmdi_metrics-2.5.1-py3.9.egg/EGG-INFO/scripts/variability_across_timescales_PS_driver.py", line 54, in <module>
IndexError: list index out of range

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[5], line 1
----> 1 get_ipython().run_cell_magic('bash', '', 'variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py\n')

File ~/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2430, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2428 with self.builtin_trap:
   2429     args = (magic_arg_s, cell)
-> 2430     result = fn(*args, **kwargs)
   2432 # The code below prevents the output from being displayed
   2433 # when using magics with decodator @output_can_be_silenced
   2434 # when the last Python token in the expression is a ';'.
   2435 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/IPython/core/magics/script.py:153, in ScriptMagics._make_script_magic.<locals>.named_script_magic(line, cell)
    151 else:
    152     line = script
--> 153 return self.shebang(line, cell)

File ~/mambaforge/envs/pmp_devel_20230218/lib/python3.9/site-packages/IPython/core/magics/script.py:305, in ScriptMagics.shebang(self, line, cell)
    300 if args.raise_error and p.returncode != 0:
    301     # If we get here and p.returncode is still None, we must have
    302     # killed it but not yet seen its return code. We don't wait for it,
    303     # in case it's stuck in uninterruptible sleep. -9 = SIGKILL
    304     rc = p.returncode or -9
--> 305     raise CalledProcessError(rc, cell)

CalledProcessError: Command 'b'variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py\n'' returned non-zero exit status 1.
```

**Comment by lee1043** [comment]
@msahn guesses that is because of xcdat code trying to load xml demo input. 

This [`xcdat_open`](https://github.com/PCMDI/pcmdi_metrics/blob/4a4b5b3b2db70ef5d4747d2a1ef89262936c51ea/pcmdi_metrics/io/xcdat_openxml.py#L9) function might be helpful.

**Comment by msahn** [comment]
I have removed the part for creating and reading xml file and modified it to read nc files directly. I think it is good to make the demo simple because reading xml file is not necessary here.

[Pull request](https://github.com/PCMDI/pcmdi_metrics/pull/901#issue-1597469205)

**Comment by lee1043** [comment]
@msahn thank you for the update! I will merge your PR once I complete reviewing it.
