### ISSUE TITLE
Run error from precipitation distribution driver

### ISSUE THREAD

**Issue by lee1043** [PCMDI/pcmdi_metrics#904]
```
$ precip_distribution_driver.py --help
```

```
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/bin/precip_distribution_driver.py", line 12, in <module>
    from pcmdi_metrics.precip_distribution.lib import (
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/pcmdi_metrics/precip_distribution/lib/__init__.py", line 2, in <module>
    from .lib_precip_distribution import (  # noqa
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/pcmdi_metrics/precip_distribution/lib/lib_precip_distribution.py", line 8, in <module>
    import rasterio.features
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/rasterio/__init__.py", line 9, in <module>
    from rasterio._base import gdal_version
ImportError: dlopen(/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/rasterio/_base.cpython-39-darwin.so, 2): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/libgdal.30.dylib
  Expected in: /Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/libblosc.1.dylib
 in /Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/libgdal.30.dylib
```

It looks like the error is associated with `rasterio`. @msahn @acordonez  have you experienced something similar?

**Comment by msahn** [comment]
I haven't experienced that error. I have tested the command, and it works well in my conda environment.

```
[ahn6@gates:~/PCMDI/pcmdi_metrics/branch/900_msa_precip_variability_demo/pcmdi_metrics/pcmdi_metrics/precip_distribution] precip_distribution_driver.py --help
usage: precip_distribution_driver.py [-h] [--parameters PARAMETERS] [--diags OTHER_PARAMETERS [OTHER_PARAMETERS ...]]
                                     [--mip MIP] [--mod MOD] [--var VAR] [--frq FRQ] [--modpath MODPATH]
                                     [--results_dir RESULTS_DIR] [--case_id CASE_ID] [--prd PRD [PRD ...]] [--fac FAC]
                                     [--res RES [RES ...]] [--ref REF] [--ref_dir REF_DIR] [--exp EXP] [--ver VER] [--cmec]
                                     [--no_cmec]

optional arguments:
  -h, --help            show this help message and exit
  --parameters PARAMETERS, -p PARAMETERS
  --diags OTHER_PARAMETERS [OTHER_PARAMETERS ...], -d OTHER_PARAMETERS [OTHER_PARAMETERS ...]
                        Path to other user-defined parameter file. (default: None)
  --mip MIP             cmip5, cmip6 or other mip (default: None)
  --mod MOD             model (default: None)
  --var VAR             pr or other variable (default: None)
  --frq FRQ             day, 3hr or other frequency (default: None)
  --modpath MODPATH     data directory path (default: None)
  --results_dir RESULTS_DIR
                        results directory path (default: None)
  --case_id CASE_ID     case_id with date (default: None)
  --prd PRD [PRD ...]   start- and end-year for analysis (e.g., 1985 2004) (default: None)
  --fac FAC             factor to make unit of [mm/day] (default: None)
  --res RES [RES ...]   list of target horizontal resolution [degree] for interporation (lon, lat) (default: None)
  --ref REF             reference data (default: None)
  --ref_dir REF_DIR     reference directory path (default: None)
  --exp EXP             e.g., historical or amip (default: None)
  --ver VER             version (default: None)
  --cmec                Use to save CMEC format metrics JSON (default: False)
  --no_cmec             Do not save CMEC format metrics JSON (default: False)
```

Below is my conda environment.
```
[ahn6@gates:~/PCMDI/pcmdi_metrics/branch/900_msa_precip_variability_demo/pcmdi_metrics/pcmdi_metrics/precip_distribution] conda list
# packages in environment at /home/ahn6/anaconda3/envs/pcmdi_metrics_dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
affine                    2.3.0              pyhd3eb1b0_0
alsa-lib                  1.2.3                h516909a_0    conda-forge
anyio                     3.5.0            py39h06a4308_0
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h7f8727e_0
asttokens                 2.0.5              pyhd3eb1b0_0
attrs                     21.4.0             pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.11.1           py39h06a4308_0
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.1               hd32f23e_0    conda-forge
bokeh                     2.4.3            py39h06a4308_0
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotli                    1.0.9                h5eee18b_7
brotli-bin                1.0.9                h5eee18b_7
brotlipy                  0.7.0           py39h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2022.9.14            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cartopy                   0.20.1           py39h8394fad_5    conda-forge
cdat_info                 8.2.1              pyhd8ed1ab_2    conda-forge
cdms2                     3.1.5           py39hdc79e2e_14    conda-forge
cdp                       1.7.0              pyhd8ed1ab_0    conda-forge
cdtime                    3.1.4            py39he83c29a_7    conda-forge
cdutil                    8.2.1              pyhd8ed1ab_1    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cf_xarray                 0.7.4              pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h74dc2b5_0
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
cftime                    1.5.1.1          py39hce1f21e_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py39h06a4308_0
click-plugins             1.1.1              pyhd3eb1b0_0
cligj                     0.7.2            py39h06a4308_0
cloudpickle               2.0.0              pyhd3eb1b0_0
coverage                  6.3.2            py39h7f8727e_0
cryptography              37.0.1           py39h9ce1e76_0
curl                      7.82.0               h7f8727e_0
cycler                    0.11.0             pyhd3eb1b0_0
cytoolz                   0.11.0           py39h27cfd23_0
dask                      2022.7.0         py39h06a4308_0
dask-core                 2022.7.0         py39h06a4308_0
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.5.1            py39h295c915_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
distarray                 2.12.2             pyhd8ed1ab_2    conda-forge
distlib                   0.3.2              pyhd3eb1b0_0
distributed               2022.7.0         py39h06a4308_0
editdistance-s            1.0.0            py39h1a9c180_2    conda-forge
entrypoints               0.4              py39h06a4308_0
eofs                      1.4.0                      py_0    conda-forge
esmf                      8.2.0           nompi_h61edca3_0    conda-forge
esmpy                     8.2.0           nompi_py39hc8aa433_1    conda-forge
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.4.4                h295c915_0
filelock                  3.6.0              pyhd3eb1b0_0
fiona                     1.8.20           py39hc5a795b_4    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freeglut                  3.2.1                h9c3ff4c_2    conda-forge
freetype                  2.11.0               h70c0345_0
freexl                    1.0.6                h27cfd23_0
fsspec                    2022.7.1         py39h06a4308_0
future                    0.18.2           py39h06a4308_1
g2clib                    1.6.3                ha7d24e7_0
gdal                      3.4.0           py39h218ed2d_11    conda-forge
genutil                   8.2.1            py39hce5d2b2_2    conda-forge
geopandas                 0.9.0                      py_1
geopandas-base            0.9.0                      py_1
geos                      3.10.1               h9c3ff4c_1    conda-forge
geotiff                   1.7.0                h90a4e78_5    conda-forge
gettext                   0.21.0               hf68c758_0
giflib                    5.2.1                h7b6447c_0
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_103    conda-forge
heapdict                  1.0.1              pyhd3eb1b0_0
icu                       68.2                 h9c3ff4c_0    conda-forge
identify                  2.3.7              pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
ipykernel                 6.9.1            py39h06a4308_0
ipython                   8.4.0            py39h06a4308_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jasper                    2.0.33               ha77e612_0    conda-forge
jbig                      2.1                  hdba287a_0
jedi                      0.18.1           py39h06a4308_1
jinja2                    3.0.3              pyhd3eb1b0_0
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9e                   h7f8727e_0
json-c                    0.15                 h98cffda_0    conda-forge
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.4.0            py39h06a4308_0
jupyter_client            7.3.4            py39h06a4308_0
jupyter_core              4.10.0           py39h06a4308_0
jupyter_server            1.18.1           py39h06a4308_0
jupyterlab                3.2.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.12.0           py39h06a4308_0
kealib                    1.4.14               h87e4c3c_3    conda-forge
kiwisolver                1.4.2            py39h295c915_0
krb5                      1.19.2               hac12032_0
lazy-object-proxy         1.6.0            py39h27cfd23_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libblas                   3.9.0           12_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcdms                   3.1.2              h3bdf4ba_117    conda-forge
libcf                     1.0.3           py39h8930027_113    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.82.0               h0b77cf5_0
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.8                  h7f8727e_5
libdrs                    3.1.2              hf593df3_118    conda-forge
libdrs_f                  3.1.2              h7e76ec7_114    conda-forge
libedit                   3.1.20210714         h7f8727e_0
libev                     4.33                 h7f8727e_1
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h295c915_4
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgdal                   3.4.0               h4471fe2_11    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libglib                   2.70.2               h174f98d_1    conda-forge
libglu                    9.0.0                hf484d3e_1
libiconv                  1.16                 h7f8727e_2
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm11                 11.1.0               h3826bc1_1
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.46.0               hce63b2e_0
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libpq                     13.5                 hd57d9b9_1    conda-forge
librttopo                 1.1.0                h30b5eef_8    conda-forge
libsodium                 1.0.18               h7b6447c_0
libspatialindex           1.9.3                h2531618_0
libspatialite             5.0.1               hf3ee066_12    conda-forge
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h7b6447c_0
libwebp                   1.2.2                h55f646e_0
libwebp-base              1.2.2                h7f8727e_0
libxcb                    1.13                 h1bed415_1
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
llvmlite                  0.38.1           py39h7d9a04d_0    conda-forge
locket                    1.0.0            py39h06a4308_0
lz4                       3.1.3            py39h27cfd23_0
lz4-c                     1.9.3                h295c915_1
mapclassify               2.4.3              pyhd3eb1b0_0
markupsafe                2.1.1            py39h7f8727e_0
matplotlib                3.4.3            py39hf3d152e_2    conda-forge
matplotlib-base           3.4.3            py39hbbc1b5f_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py39h27cfd23_1000
msgpack-python            1.0.3            py39hd09550d_0
munch                     2.5.0              pyhd3eb1b0_0
munkres                   1.1.4                      py_0
mysql-common              8.0.27               ha770c72_3    conda-forge
mysql-libs                8.0.27               hfa10184_3    conda-forge
nb_conda                  2.2.1            py39hf3d152e_4    conda-forge
nb_conda_kernels          2.3.1            py39hf3d152e_1    conda-forge
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13           py39h06a4308_0
nbconvert                 6.4.4            py39h06a4308_0
nbformat                  5.3.0            py39h06a4308_0
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.5            py39h06a4308_0
netcdf-fortran            4.5.3           nompi_h2b6e579_106    conda-forge
netcdf4                   1.5.7            py39ha0f2276_1
networkx                  2.8.4            py39h06a4308_0
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12           py39h06a4308_0
nspr                      4.33                 h295c915_0
nss                       3.74                 h0370c37_0
numba                     0.55.2           py39h66db6d7_0    conda-forge
numpy                     1.21.3           py39hdbf815f_1    conda-forge
openblas                  0.3.18          pthreads_h4748800_0    conda-forge
openjpeg                  2.4.0                h3ad879b_0
openssl                   1.1.1q               h166bdaf_0    conda-forge
output_viewer             1.3.3              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.2.4            py39h2531618_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_1
patsy                     0.5.2            py39h06a4308_1
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.0.1            py39h22f2fdc_0
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h7f8727e_1
pluggy                    1.0.0            py39h06a4308_1
pooch                     1.4.0              pyhd3eb1b0_0
poppler                   21.11.0              ha39eefc_0    conda-forge
poppler-data              0.4.11               h06a4308_0
postgresql                13.5                 h2510834_1    conda-forge
pre-commit                2.15.0           py39hf3d152e_1    conda-forge
pre_commit                2.15.0               hd8ed1ab_1    conda-forge
proj                      8.2.0                h277dcde_0    conda-forge
prometheus_client         0.14.1           py39h06a4308_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
psutil                    5.9.0            py39h5eee18b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0             pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py39h06a4308_0
pyproj                    3.3.0            py39h1b810de_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
pyrsistent                0.18.0           py39heee7806_0
pyshp                     2.1.3              pyhd3eb1b0_0
pysocks                   1.7.1            py39h06a4308_0
pytest                    6.2.5            py39hf3d152e_2    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
python                    3.9.9           h62f1059_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39h06a4308_0
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1           py39h06a4308_0
pyyaml                    6.0              py39h7f8727e_1
pyzmq                     23.2.0           py39h6a678d5_0
qt                        5.12.9               hda022c4_4    conda-forge
rasterio                  1.2.10           py39he0fb565_3    conda-forge
readline                  8.1                  h27cfd23_0
regionmask                0.9.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.1           py39h06a4308_0
rtree                     0.9.7            py39h06a4308_1
scikit-learn              1.1.1            py39h6a678d5_0
scipy                     1.7.3            py39hee8e79c_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                63.4.1           py39h06a4308_0
shapely                   1.8.0            py39h98e2149_4    conda-forge
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h295c915_0
sniffio                   1.2.0            py39h06a4308_1
snuggs                    1.4.7              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.1              pyhd3eb1b0_0
sparse                    0.13.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               hc218d9a_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.13.2           py39h7f8727e_0
tblib                     1.7.0              pyhd3eb1b0_0
terminado                 0.13.1           py39h06a4308_0
testpath                  0.6.0            py39h06a4308_0
threadpoolctl             2.2.0              pyh0d69192_0
tiledb                    2.5.3                h2038895_0    conda-forge
tk                        8.6.11               h1ccaba5_0
toml                      0.10.2             pyhd3eb1b0_0
toolz                     0.11.2             pyhd3eb1b0_0
tornado                   6.1              py39h27cfd23_0
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.3.0            py39h06a4308_0
typing_extensions         4.3.0            py39h06a4308_0
tzcode                    2022a                h166bdaf_0    conda-forge
tzdata                    2022a                hda174b7_0
udunits2                  2.2.25               hd30922c_1
urllib3                   1.26.11          py39h06a4308_0
virtualenv                20.4.6           py39h06a4308_1
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39h06a4308_1
websocket-client          0.58.0           py39h06a4308_4
wheel                     0.37.1             pyhd3eb1b0_0
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xcdat                     0.3.1              pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h9d8b166_3    conda-forge
xesmf                     0.6.3              pyhd8ed1ab_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xz                        5.2.5                h7f8727e_1
yaml                      0.2.5                h7b6447c_0
zeromq                    4.3.4                h2531618_0
zict                      2.1.0            py39h06a4308_0
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha4553b6_1
```

**Comment by lee1043** [comment]
@msahn thank you for checking. I confirm it works well after I recreated my conda environment. I am closing this issue.
